# The following line is needed
# when running the example site
# from a subdir of the theme
themesDir = "themes"

title = "Neil Thomas"
theme = "not-much"
languageCode = "en-us"
baseURL = "https://www.neiltthomas.com/"
copyright = "© {year} Neil Thomas"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "dark"
palette = "default"
showThemeNotice = false

# SEO Configuration
[params.seo]
  title = "Neil Thomas - EECS Student at UC Berkeley"
  description = "Personal website of Neil Thomas, Electrical Engineering and Computer Science student at UC Berkeley"
  keywords = ["Neil Thomas", "UC Berkeley", "EECS", "Electrical Engineering", "Computer Science"]
  author = "Neil Thomas"
  twitter = "@neiltthomas"  # Update with your actual Twitter handle
  og_image = "/images/og-image.jpg"  # Add an Open Graph image for social sharing

# Enable robots.txt
enableRobotsTXT = true

# Enable sitemap
enableSitemap = true

# Navigation
[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "Bookshelf"
    name = "Bookshelf"
    title = "BookShelf"
    url = "/bookshelf"
    weight = 2
  

  [[menu.main]]
    identifier = "author"
    name = "Author"
    title = "Author"
    url = "/author/"
    weight = 3

